name: dwhois
description: A simple whois client in Dart
version: 2.0.0
repository: https://github.com/Ascenio/dwhois

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
